# Sidebar navigation

- label: 'Main commands'
  link: '/'
- label: React
  items:
    - label: 'Class component'
      link: '/react/class-component'
    - label: 'Functional component'
      link: '/react/functional-component'
- label: Redux
  items:
    - label: 'State global'
      link: '/'

- label: Usage
  items:
    - label: 'creating-docs'
      link: '/usage/creating-docs'
    - label: 'navigation'
      link: '/usage/navigation'
    - label: 'Shadowing'
      link: '/usage/shadowing'
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: Changelog
      link: /changelog
- label: Community
  items:
    - label: 'Github'
      link: https://github.com/rocketseat/gatsby-themes
